services:
  # =============================================================================
  # NATS Server
  # =============================================================================\
  nats-server:
    image: nats:latest

  # =============================================================================
  # Auth Microservice
  # =============================================================================\
  auth-microservice:
    build:
      context: ./auth-microservice
      dockerfile: Dockerfile.prod
      args:
        - AUTH_MICROSERVICE_DATABASE_URL=${AUTH_MICROSERVICE_DATABASE_URL}
    image: auth-microservice-prod
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${AUTH_MICROSERVICE_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}

  # =============================================================================
  # Client Gateway
  # =============================================================================\
  client-gateway:
    build:
      context: ./client-gateway
      dockerfile: Dockerfile.prod
    image: client-gateway-prod
    ports:
      - ${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}
    environment:
      - PORT=${CLIENT_GATEWAY_PORT}
      - NATS_SERVERS=nats://nats-server:4222

  # =============================================================================
  # Products Microservice
  # =============================================================================\
  products-microservice:
    build:
      context: ./products-microservice
      dockerfile: Dockerfile.prod
    environment:
      - PORT=3001
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=file:./dev.db

  # =============================================================================
  # Orders Microservice
  # =============================================================================\
  orders-microservice:
    build:
      context: ./orders-microservice
      dockerfile: Dockerfile.prod
      args:
        - ORDERS_MICROSERVICE_DATABASE_URL=${ORDERS_MICROSERVICE_DATABASE_URL}
    environment:
      - PORT=3002
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${ORDERS_MICROSERVICE_DATABASE_URL}

  # =============================================================================
  # Payments Microservice
  # =============================================================================\
  payments-microservice:
    build:
      context: ./payments-microservice
      dockerfile: Dockerfile.prod
    ports:
      - ${PAYMENTS_MICROSERVICE_PORT}:${PAYMENTS_MICROSERVICE_PORT}
    environment:
      - PORT=${PAYMENTS_MICROSERVICE_PORT}
      - NATS_SERVERS=nats://nats-server:4222
      - STRIPE_SECRET=${STRIPE_SECRET}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
